---
title: "Optional code"
format: html
editor: visual
---

## Visualization

```{r}
## RGB
par(col.axis = "white", col.lab = "white", tck = 0)
plotRGB(landsat.crop21,
     r = 4, g = 3, b = 2,
     stretch = "lin", 
     axes = TRUE,
     main = "RGB composite image\n Landsat Bands 4, 3, 2")
box(col = "white")

## Near infrared
par(col.axis = "white", col.lab = "white", tck = 0)
plotRGB(landsat.crop21,
     r = 5, g = 4, b = 3,
     stretch = "lin",
     axes = TRUE,
     main = "Color infrared composite image\n Landsat Bands 5, 4, 3")
box(col = "white")
```

```{r}
## NDVI
NDVIwolv <- (landsat.crop21[[5]]-landsat.crop21[[4]])/(landsat.crop21[[5]]+landsat.crop21[[4]])
NDVI.ter <- terra::rast(NDVIwolv)
#NDVIsmooth<- focal(NDVI.ter, w=5, fun= modal, na.policy= "all") #I think smoothing looks bad

plot(NDVIwolv,
     main ="NDVI of Wolverine Glacier Watershed",
     axes = FALSE, box = FALSE)

 hist(NDVIwolv)

#attempt to isolate just vegetation
veg <- clamp(NDVIwolv, 0.0, values=FALSE) 
plot(veg, main="Vegetation")
```

## Save land cover rasters

```{r}
#raster export
writeRaster(wolv.cover, filename = "wolvlandcov.asc", )

#pdf
pdf(filename ="wolvfiguretest2.pdf", 
         res= 72  
  )
raster::plot(wolv.cover,
     col= covcol, 
     axes=FALSE
    )
sbar(4000, xy="bottomright", type="bar",divs=4)
dev.off()

pdf(file ="shrubfig.pdf")
terra::plot(shrub.cover, 
     col= covcol, 
     axes=FALSE,
     legend=FALSE)
terra::sbar(1000, xy="bottomright", type="bar",divs=4)

pdf(file ="njfigure.pdf")
terra::plot(nj.cover, 
     col= covcol, 
     axes=FALSE, 
     legend= FALSE
     )
terra::sbar(10000, xy="bottomright", type="bar",divs=4)

pdf(file ="tundrafig.pdf")
terra::plot(tundra.cover, 
     col= covcol, 
     axes=FALSE,
     legend=FALSE)
terra::sbar(1000, xy="bottomright", type="bar",divs=4)

pdf(file ="glacierfig.pdf")
terra::plot(glacier.cover, 
     col= covcol, 
     axes=FALSE,
     legend=FALSE)
terra::sbar(1000, xy="bottomright", type="bar",divs=4)

pdf(file ="forestfig.pdf")
terra::plot(forest.cover, 
     col= covcol, 
     axes=FALSE,
     legend=FALSE)
terra::sbar(100, xy="bottomleft", type="bar",divs=4)
```

## 

```{r}

library(tidyverse)
colnames(traindf) <- c('class','band1','band2','band3','band4','band5','band6','band7')

#create a dataframe of mean band values of each landcover type
profiles <- traindf %>% 
  as.data.frame() %>% 
  cbind(., trainingSpatial$id) %>% 
  dplyr::rename(id = "trainingSpatial$id") %>% 
  na.omit() %>% 
  group_by(id) %>% 
  dplyr::summarise(band1 = mean(band1),
            band2 = mean(band2),
            band3 = mean(band3),
            band4 = mean(band4),
            band5 = mean(band5),
            band6 = mean(band6),
            band7 = mean(band7)) %>% 
  mutate(id = case_when(id == 1 ~ "icesnow",
                        id == 2 ~ "tundra",
                        id == 3 ~ "forest",
                        id == 4 ~ "shrub",
                        id == 5 ~ "rockwater")) %>% 
  as.data.frame()

head(profiles)
```

Spectral profile of bands

```{r}
profiles %>% 
  select(-id) %>% 
  gather() %>% 
  mutate(class = rep(c("icesnow", "tundra", "forest","shrub", "rockwater"), 7)) %>% 
  ggplot(data = ., aes(x = fct_relevel(as.factor(key),
                                       levels = c("band1", "band2", "band3", "band4"
                                                  ,"band5","band6", "band7")), 
                       y = value, 
                       group=class, color = class)) +
  geom_point(size = 2.5) +
  geom_line(lwd = 1.2) +
  scale_color_manual(values=c('#448970', 'snow2', '#828282','#FFA77F','#D1FF73')) +
  labs(title = "Spectral Profile from Landsat 8 Imagery",
       x = "Bands",
       y = "Reflectance") +
  #scale_y_continuous(limits=c(5000, 15000)) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_line(color = "gray", size = 0.5),
        panel.grid.minor = element_line(color = "gray", size = 0.5),
        axis.ticks = element_blank())
```

Density of bands

```{r}
profiles %>% 
  select(-id) %>% 
  gather() %>% 
  mutate(class = rep(c("icesnow", "tundra", "forest","shrub", "rockwater"), 7)) %>% 
  ggplot(., aes(x=value, group=as.factor(class), fill=as.factor(class))) + 
  geom_density(alpha = 0.5) + 
  geom_vline(data = . %>% group_by(class) %>% dplyr::summarise(grp.mean = mean(value)),
             aes(xintercept=grp.mean, color = class), linetype="dashed", size=1) +
 # scale_color_manual(values=c('darkgreen','snow', 'dimgray', 'darkseagreen3',
  #                            'darkolivegreen4')) +
  theme(panel.background = element_blank(),
        panel.grid.major = element_line(color = "gray", size = 0.5),
        panel.grid.minor = element_line(color = "gray", size = 0.5),
        axis.ticks = element_blank()) +
  labs(x = "Reflectance Value",
       y = "Density",
       title = "Density histograms of spectral profiles",
       subtitle = "Vertical lines represent mean group reflectance values")
```
